### ISSUE TITLE
You always delete the latest name of gesture/class when you delete any gesture/class

### ISSUE THREAD

**Issue by Karlo-Emilo** [microbit-foundation/cctd-ml-machine#392] opened 2023-11-24 12:08 UTC
Result: The wrong name is removed on the screen and the name and data is mixed (only in the UI) until the component is remounted.

recreate:
Have more then one classes and delete a class that is not the newest added (the last on the list).

**Comment by Karlo-Emilo** [comment] 2023-11-24 13:01
@r59q, I am not that I understand how this is implemented. Will you look at it? This is on the live version, so it is high priority to get it fixed.

**Comment by r59q** [comment] 2023-11-24 20:11
> @r59q, I am not that I understand how this is implemented. Will you look at it? This is on the live version, so it is high priority to get it fixed.

I will look into it this during this weekend. Hopefully fixed by sunday/monday.

 I am not entirely sure what the issue is, but I will look into it. If you read this before it is solved, please provide details

**Closed** 2023-11-25 19:57 UTC
Labels: bug
