### ISSUE TITLE
Updating the micro:bits slows connection with bluetooth

### ISSUE THREAD

**Issue by bubblebreak** [microbit-foundation/cctd-ml-machine#483] opened 2024-05-16 09:12 UTC
on wednesday (15/05/24) a set og micro:bits (V. 2.21) were updated with the latest firmware from the micro:bit developer community page (Interface 0257). When updating the firmware and downloading the ml-machine program onto the micro:bit, no issues were identified. Connecting the micro:bit through Bluetooth works fine for the first couple of steps - you can draw the pattern and pick it out in the port selector. However, it then attempts to connect for a very long period of time (several minutes). 
Upon rolling back to a previous firmware version, no issues were identified other than the page requesting an update of the micro:bit firmware. The ml-machine system worked fine upon ignoring the update request.

**Comment by r59q** [comment] 2024-05-16 09:57
Thank you for the report, I will investigate the issue, this was using the ml-machine.org website, right?

**Comment by bubblebreak** [comment] 2024-05-16 09:59
Yes, only the ml-machine.org page

**Comment by r59q** [comment] 2024-05-23 20:42
The code that causes the broken firmware prompt is the following
```ts
function onFoundUsbDevice() {
    Microbits.getLinkedFriendlyName()
      .then(friendlyName => {
        ....
      })
      .catch((e: Error) => {
        // Couldn't find name. Set to manual transfer progress instead
        if (e.message.includes('No valid interfaces found')) {
          // Edge case, caused by a bad micro:bit firmware
          $connectionDialogState.connectionState = ConnectDialogStates.BAD_FIRMWARE;
        } else {
          $connectionDialogState.connectionState = ConnectDialogStates.MANUAL_TUTORIAL;
        }
      });
  }
```
which would only happen during the WebUSB flashing process.

The other prompt is when our own micro:bit program is outdated, which it determines by self-identifying versions via UART messages. The only way for this prompt to **reappear** is if the program(our .hex) has been downgraded to a previous version (or it's the case where the identification message fails to appear after connecting, which will be resolved in the future)

So unless **both** the firmware and our program has been downgraded, the outdated program prompt is actually unrelated to this case.

However I do not have a 2.21 microbit to test this with. Using the 0257 firmware on my 2.20, I was unable to replicate this issue. @Karlo-Emilo do you have a 2.21 micro:bit?

From what I can gather, we need to test a 2.21 microbit, with the 0257 firmware. In this case, we should, from my understanding be able to flash the hex, but the connection is sluggish. Then downgrading to 256 should solve the issue without flashing our microbit program again.

Note: The 257 firmware should work with both 2.20 and 2.21, but the 256 version isn't intended for 2.20, so if this is the case, we might need to investigate further

**Comment by Karlo-Emilo** [comment] 2024-05-24 08:18
@r59q, you can find a micro:bit v2.21 on my desk (apparently in a goodie bag). Will you be able to pick it up there?

**Comment by r59q** [comment] 2024-05-24 08:27
> @r59q, you can find a micro:bit v2.21 on my desk (apparently in a goodie bag). Will you be able to pick it up there?

I will thanks 👍

**Comment by r59q** [comment] 2024-05-25 14:12
I have tried both downgrading and updating the microbit firmware, used previous versions of our micro:bit program, using the 2.21 micro:bit and i couldn't seem to replicate the issue. I will keep this open for a little while, but i have the feeling that the issue isn't on our side. At least this didn't seem to be an issue on chrome for macos nor chromium for linux

**Comment by r59q** [comment] 2024-08-21 19:09
Closing, can't replicate

**Closed by r59q** 2024-08-21 19:09 UTC
Labels: bug, can't replicate
